### ISSUE TITLE
Links in getBC430 are dead

### ISSUE THREAD

**Issue by MikkoPontinen** [oorb/oorb#100]
The links used in getBC430 to download BC430 asteroid ephemerides don't work.

**Comment by mgranvik** [comment]
@Siltala can you update the download of BC430 files to reflect their current location at https://zenodo.org/record/3558850/files/BC430.tar.gz

**Comment by mgranvik** [comment]
@Siltala, @mjuric & @rhiannonlynne: the discussion apparently disappeared when I ran 

git reset --hard 475dc9db246bb3380e7d91f6e51fc3cb841f484a                                                                      
git push --force

**Comment by mgranvik** [comment]
@mjuric, @rhiannonlynne : the size of the repo is still 58.2MB so I presume the file is still in the history. Do you have any other suggestions for how to delete the file from the history?

**Comment by mjuric** [comment]
@mgranvik: It's remained only in your local clone. Two steps to get rid of it:
* Make sure you delete any branches that refer to the old commit. E.g., run `git branch -a` and see if there are any that refer to the pull request with the file. Then delete them with `git branch -D`.
* Then try running:
```
git reflog expire --expire-unreachable=now --all
git gc --prune=now
```
(as per [this](https://stackoverflow.com/questions/3765234/listing-and-deleting-git-commits-that-are-under-no-branch-dangling/4528593#4528593)).

Things look good when you clone the repository from scratch:
```
[mjuric@gallifrey (master) ~/projects/github/oorb/oorb/foo]$ git clone git@github.com:oorb/oorb
Cloning into 'oorb'...
remote: Enumerating objects: 2081, done.
remote: Total 2081 (delta 0), reused 0 (delta 0), pack-reused 2081
Receiving objects: 100% (2081/2081), 1.29 MiB | 8.23 MiB/s, done.
Resolving deltas: 100% (1421/1421), done.
[mjuric@gallifrey (master) ~/projects/github/oorb/oorb/foo]$ du -d 1 oorb/.git
2776	oorb/.git/objects
8	oorb/.git/info
24	oorb/.git/logs
96	oorb/.git/hooks
16	oorb/.git/refs
2976	oorb/.git
[mjuric@gallifrey (master) ~/projects/github/oorb/oorb/foo]$
```
(which, depending on how much local history you have, may be an easier option).

Or you can just ignore it :) -- it'll occupy an extra 50M on *your* hard drive, but it's not in the main repo any more.

**Comment by mjuric** [comment]
@mgranvik I can see the discussion on the old PR if I go to https://github.com/oorb/oorb/pull/101 (it's closed so it doesn't how up in the Issue list by default). - hth.
