### ISSUE TITLE
oorb does not run if compiled with gfortran 5.x

### ISSUE THREAD

**Issue by rhiannonlynne** [oorb/oorb#12]
OOrb compiles and runs as expected with gfortran 4.9. 
However, newer compilers (gfortran 5 or newer) produce the following error at runtime: 

[D-108-179-173-36:~/lsstRepos/oorb/python] lynnej% ../main/oorb --code=807 --task=ephemeris --orb-in=test_orbits.des --timespan=1 --step=1 --conf=../main/oorb.conf
oorb(13219,0x7fff7653b300) malloc: *** error for object 0x2: pointer being freed was not allocated
*** set a breakpoint in malloc_error_break to debug

Program received signal SIGABRT: Process abort signal.

Backtrace for this error:
#0  0x1006621d2
#1  0x1006614f0
#2  0x7fff8e581f19

(note that oorb will appear to compile as expected, but will not generate ephemerides).

**Comment by Siltala** [comment]
Hello,

I tested this and can reproduce the bug. Though my error message isn't exactly the same, --task=ephemeris also fails for me when compiled with gfortran 5.1. On that note, ranging and lsl both fail also while they all work on an earlier gfortran version.

I think I also figured out the problem, and managed to fix ephemeris, ranging and lsl on my end. Can you please test my fork ( https://github.com/Siltala/oorb ) to see if it works for you as well? Note that at this point, my fixes are just quick hacks and at this point it might not be a good idea to use my fork for any serious work beyond testing if it works, though I can't personally see any major problems arising from my fix. I'll discuss the problem and how to fix it with Mikael later this week. (I am a student of his, if you are curious.)

What seems to be happening here is that the behavior of ASSOCIATED() appears to have changed in gfortran 5. In several parts of the code, oorb appears to use ASSOCIATED() to check if some variable exists, and if it does, oorb next deallocates it. Now, this works fine in older gfortran versions, but as far as I can tell, in gfortran 5 ASSOCIATED() returns true even if the variable doesn't exist. So, the code then tries to deallocate it anyway which leads to the crash.

Lauri

**Comment by rhiannonlynne** [comment]
Thanks very much for the quick response! 
I tested your fork with gfortran 5.2.0. 
It doesn't seem like it's working for me though: now I have this error (using the generic oorb.conf that comes with the repo, and after building oorb using ./configure gfortran opt and building the de405 file). 

[ewok:~/otherRepos/oorb/python] lynnej% ../main/oorb --task=ephemeris --orb-in=test.des --code=807 --timespan=1 --step=1
***ERROR*** 20 Oct 2015 20:30:09UTC (Orbit / setParameters) Option  not available.
***ERROR*** 20 Oct 2015 20:30:09UTC (oorb / ephemeris) TRACE BACK (15)

(maybe this is something else ? test.des looks "normal" and is a file that worked with a previously compiled version of oorb -- here's it's contents:
 !!OID FORMAT q e i node argperi t_p H t_0 INDEX N_PAR MOID COMPCODE
1 COM 0.124956085532573E+01 0.383012706301957E+00 0.931089594851032E+01 0.252175870225517E+03 0.185475213571715E+03 0.498552191422642E+05 0.103150000000000E+02 0.493531606965741E+05 1 6 -0.100000000000000E+01 OPENORB
2 COM 0.128992479963442E+01 0.661595944036122E+00 0.183021914914764E+02 0.132767038439005E+03 0.801372893930835E+02 0.492274900056936E+05 0.108180000000000E+02 0.493531606965741E+05 1 6 -0.100000000000000E+01 OPENORB
)

**Comment by rhiannonlynne** [comment]
Okay, it looks like ephemeris generation works perfectly thank you! 

I may still be having a problem with ranging though (I don't actually need to use this, but figured I should test it). 

[ewok:~/otherRepos/oorb/test] lynnej% ../main/oorb --task=ranging --obs-in=K08K42V_ranging.mpc --orb-out=K08K42V_ranging.des --conf=../main/oorb.conf
  WARNING: NOT using dchi2 in acceptance!
  WARNING: REGULARIZATION is OFF!

Program received signal SIGSEGV: Segmentation fault - invalid memory reference.

Backtrace for this error:
#0  0x1096531d2
#1  0x1096524f0
#2  0x7fff97851f19
#3  0x1094b845e
#4  0x10954e882
#5  0x10958943a
#6  0x10942e155
#7  0x1095f2ece
Segmentation fault

Running the same command with my old oorb (compiled with gfortran 4.9) doesn't produce the same error, although it runs extremely slowly. (hasn't finished yet).

**Comment by Siltala** [comment]
Hmm. It seems I can reproduce the crash with ranging if I compile with optimization on, but with debugging options it doesn't occur. I'll look into it. Anyway, I'm glad to hear my ephemerides fix works for you. Thanks for testing!

**Comment by rhiannonlynne** [comment]
Oh - I did have optimization on! So that matches my experience.

**Comment by mgranvik** [comment]
I've solved this issue by ensuring that all pointers are pointed at null() when defined. This solved the compilation issue with gfortran 5. Note that I will not pull Lauri's solution because that would lead to a potential memory leak later on.
