### ISSUE TITLE
Feature request: create storb objects without uncertainty information

### ISSUE THREAD

**Issue by Siltala** [oorb/oorb#122]
Hi,

For my asteroid close encounter finding code I would like to use the mass_estimation_march task with orbits from MPCORB to keep things simple. As there is no uncertainty information there, using MPCORB will not create storb_arr_in objects.

At the same time, for my purposes, I need storb objects but don't need orbital uncertainty information, so I'm asking for storb_arr_in to be created even if it doesn't exist.

Can you take a look at this at some point? Otherwise, I might end up trying to hack it in myself.

**Comment by mgranvik** [comment]
The fundamental aspect of the StochasticOrbit class is that it contains 
information about the uncertainty. Hence allowing instances of StochasticOrbit 
without the uncertainty information would be wrong by definition. So I think the 
right way to proceed is to figure out why you think you need a StochasticOrbit 
without its most fundamental piece of information, and then find another 
solution that doesn't require StochasticOrbit in the first place. In the case of 
mass_estimation_march, the necessary information is probably stored in variables
orb_arr_in and obss_in (or something along those lines).

So as summary: there will not be an option to initiate a StochasticOrbit object 
without uncertainty information.

Mikael

**Comment by Siltala** [comment]
Yes, for now as we discussed I have taken the approach of 'cheating' the system by giving my orbits matrices as covariance matrices. It's working out just fine for this case so far.
