### ISSUE TITLE
Asteroid perturbation files missing from conda-installed version

### ISSUE THREAD

**Issue by fedorets** [oorb/oorb#132]
This is a super minor issue, but it seems that the conda-installed version is lacking the three asteroid perturbation files. As n-body in the configuration file assumes asteroid perturbations to be True by default, it leads to n-body calculations to crash by default. Nothing that changing asteroid perturbations to False wouldn't fix but could be a nuisance for a less experienced OpenOrb user.

**Comment by Siltala** [comment]
Hi Grigori,

Asteroid perturbers are actually disabled by default: https://github.com/oorb/oorb/blob/master/main/oorb.conf
though that could be different with the conda version if they ship a modified version for some reason. Anyway, the files in question should be provided by the `openorb-data-bc430` package as documented in the Wiki ( https://github.com/oorb/oorb/wiki/Installation )
