### ISSUE TITLE
PyPI release

### ISSUE THREAD

**Issue by spenczar** [oorb/oorb#135]
I would like to install pyoorb as a dependency of a production service. I'd like to install it with pip, since pip runs more quickly than conda, and it has adjacent tools like [pip-compile](https://github.com/jazzband/pip-tools) which are very helpful for building stable services. Conda is great for individual users' workstations, but it is not very suited for headless servers.

I think accomplishing this would require bundling the compiled Fortran code as a binary extension in a Python wheel, like with `f2py`. This appears to be basically how the existing Python build process works, so it should be possible. Then, it would be a matter of automating the build process, running it for multiple platforms, and uploading artifacts to PyPI.

**Comment by mgranvik** [comment]
Hi  @spenczar,

I think enabling installation with pip is a great idea. As long as it doesn't break any existing features (such as installation with conda) I'm happy to accept PRs that make it happen.

Cheers,
Mikael

**Comment by Siltala** [comment]
Hi,

I also support the idea but can't promise to work on this anytime soon. In case anyone else wants to take a look, I note that we already have automated test builds done by Github Actions. It is possible to use Github Actions to also automatically publish new versions to pip whenever e.g. a new version is tagged, so I would strongly support this approach as (at least in theory) it won't really need any work from us once the initial support is implemented.

https://packaging.python.org/guides/publishing-package-distribution-releases-using-github-actions-ci-cd-workflows/

**Comment by Siltala** [comment]
https://pypi.org/project/pyoorb/
We are on PyPI now, so I am happy to close this one! :)
