### ISSUE TITLE
Confusing units in pyoorb docs

### ISSUE THREAD

**Issue by TomWagg** [oorb/oorb#142]
In [README.rst](https://github.com/oorb/oorb/blob/master/python/README.rst), under "[Defining Orbits](https://github.com/oorb/oorb/blob/master/python/README.rst#defining-orbits)" there are a list of the 12 parameters necessary. Although it does say below this list that all angles should be in radians, the units in the list are degrees "(deg)" and so I got a bit confused about why I was getting errors until I realised I had the wrong unit.

I'd recommend changing these to "(rad)" for clarity 🙂

**Comment by mgranvik** [comment]
The Fortran version of OpenOrb uses degrees only in input and output although the computations under the hood use radians only. I suspect that the mixup on the Python side _may_ be a result of copying the descriptions from the Fortran side. Is there a good reason to use radians in the input? I think most of the common orbit formats (MPC, ASTORB, etc) report angles in degrees, so one needs to convert them before input.

**Comment by mgranvik** [comment]
I've updated the documentation.
