### ISSUE TITLE
Can't compile oorb due to missing fix-rpath.sh

### ISSUE THREAD

**Issue by mgranvik** [oorb/oorb#144]
Hi @mjuric,

the installation process nowadays requires something called fix-rpath.sh. Which package includes the correct version of that script?

I'm a bit concerned that the installation procedure has become too complex to handle for those of us wanting to focus on the Fortran development, and thus not relying on the packaged products.

Cheers,
Mikael

**Comment by mjuric** [comment]
Hi @mgranvik -- it's in `build-tools/fix-rpath.sh` (together with other helper scripts). That path should be automatically picked up by the Makefile from `make.config` (see https://github.com/oorb/oorb/blob/master/make.config#L32).

Are you building it in a different way (e.g., w/o running `./configure`, or something else)?

**Comment by mgranvik** [comment]
Thanks and apologies for the false alarm, @mjuric. Earlier I ran 

make clean
./configure gfortran opt
make

but it failed. Now I tried it again, and it magically works. Can't explain why. Well problem solved anyway.

**Comment by mjuric** [comment]
Glad it worked! Do let me know if it happens again (if there's a difficult-to-trigger bug I'd love to figure it out!).
