### ISSUE TITLE
Test case comparison

### ISSUE THREAD

**Issue by rhiannonlynne** [oorb/oorb#17]
This is an example object for which we have attempted to generate positions and information from JPL tools and from OOrb and found disagreement. Any ideas on the source of the problem?

Initial orbit: 
!!OID FORMAT q e i node argperi t_p H t_0 INDEX N_PAR MOID COMPCODE
test COM 0.682084069033 0.540590690499 2.720497800946 314.400746000785 256.929800925527 54770.509283572 10.000000 54466.000000000 1 6 1 HORIZONS

(we tested converting this orbit to cartesian format and back, then back and forth again .. the round-trip is successful to the sub-m level). 

----
Propagate to 1996 (from the original 2008 epoch) and generate ephemeris, using JPL tools:
@ 50100.36672 comparison of position:
JPL solution (RA, DEC, EPOCH)
141.711815307104 23.7960976997533 50100.36672

and more x/y/z coordinate details:
JPL Prediction at 1996-Jan-18 08:48 for code 807:
T_INI= 2450100.36672
X_INI -0.517682378128683 0.943248570273295 0.0138926673375748
V_INI -0.00998928226996381 -0.015808708337284 -0.000855782305461691

ET, UT: 50100.3674396757 50100.3667199998

X_OBJ -0.52266867184861 0.935304708306426 0.0134637474765193
V_OBJ -0.00992699408359701 -0.0159211488345263 -0.000857426265364538
X_EMI -0.522663329718481 0.935313276079784 0.0134642088913595
V_EMI -0.0099270617751788 -0.0159210277351197 -0.000857424514590214
X_EAR -0.455709608010423 0.87189992496842 4.24882940514015e-06
V_EAR -0.0155359863515486 -0.00803366185969467 -3.62566342809734e-07
X_OBS -0.4557464890272 0.871892436677645 -1.57456761292751e-05
V_OBS -0.0155428095495517 -0.00824690074520342 9.20848940911051e-05
R_OBS -0.0669168367280867 0.0634208404611714 0.0134799544634611
 (R_OBS is the aberrated position of the obect with respect to the observer)

----

Propagate to 1996 and generate ephemeris, using Oorb:

oorb --task=propagation --orb-in=tjpl.des --epoch-mjd-tt=50100.3674396757 --conf=oorb.conf --orb-out=tjpl_96.des
oorb --task=ephemeris --orb-in=tjpl_96.des --code=807 | awk '{print $3, $5, $6, $4, $29, $30, $31, $32, $33, $34, $35, $36, $37}'
MJD_UTC/UT1 RA Dec Delta HEclObj_X HEclObj_Y HEclObj_Z HEclObj_dX/dt HEclObj_dY/dt HEclObj_dZ/dt HEclObsy_X HEclObsy_Y HEclObsy_Z
50100.3667202778 141.7331149446 23.7892157209 0.0931690463 -0.5226815605 0.9352840937 0.0134627463 -0.0099268203 -0.0159214282 -0.0008574418 -0.4557464972 0.8718924324 -0.0000155979

Earth still off by about 22km in z:

(oorb_obs - jpl_obs) * au2m / 1000.
array([ -1.22265088, -0.63993569, 22.10730894])
but now the emitter location is also off by a large amount.

(oorb_xyz - jpl_xyz) * au2m / 1000.
array([-2727.32491525, -4365.68401569, -218.80366738])

(and double-checking the propagation using cartesian elements -- no difference in xyz although 0.01" difference in ra)
oorb --task=propagation --orb-in=tjpl2.des --epoch-mjd-tt=50100.3674396757 --conf=oorb.conf --orb-out=tjpl_c_96.des
oorb --task=ephemeris --orb-in=tjpl_c_96.des --code=807 | awk '{print $3, $5, $6, $4, $29, $30, $31, $32, $33, $34, $35, $36, $37}'
MJD_UTC/UT1 RA Dec Delta HEclObj_X HEclObj_Y HEclObj_Z HEclObj_dX/dt HEclObj_dY/dt HEclObj_dZ/dt HEclObsy_X HEclObsy_Y HEclObsy_Z
50100.3667202778 141.7331111635 23.7892169364 0.0931690475 -0.5226815572 0.9352840989 0.0134627466 -0.0099268203 -0.0159214281 -0.0008574418 -0.4557464972 0.8718924324 -0.0000155979

Any suggestions?

(tagging @stevechesley too)

**Comment by mgranvik** [comment]
@rhiannonlynne: can you verify that fixing issue #16 also fixed this one?

**Comment by rhiannonlynne** [comment]
With the update, the difference in the observer position is as expected 
(>>> (oorb_obs - jpl_obs) * au2m/1000.
array([-1.22265088, -0.63993569, -0.66181106])  --- the 1km in x is due to de431 vs de405). 
So the fix did fix the position of the Earth. 

However, the emitter position is still off by the same amount in x and y: 

>>> (oobs_emit - jpl_emit) * au2m / 1000.
array([-2903.56867525, -4649.80433568,  -233.35974738])

when repeating the test detailed above. 

The RA/Dec values of the ephemeris do not match the expected values either: 

OORB: MJD_UTC/UT1 RA Dec Delta
50100.3667202778 141.7345397409 23.7888667347 0.0931686084

JPL: MJD_UTC RA Dec
50100.36672 141.711815307104 23.7960976997533

(still a 82" difference in RA, 26" difference in Dec).

**Comment by rhiannonlynne** [comment]
Just to check, I changed the integration_step for the integrator in the oorb.conf file (I have the dynamical model set to n-body and all perturbers are "T") to a much smaller value .. (the default is 1.0 days and I tried reducing this by a few orders of magnitude). The propagation took much longer, but the final result was essentially same (I'm guessing this is what you'd expect, but since I didn't know any better, I figured I'd try it). 

MJD_UTC/UT1 RA Dec Delta HEclObj_X HEclObj_Y HEclObj_Z HEclObj_dX/dt HEclObj_dY/dt HEclObj_dZ/dt HEclObsy_X HEclObsy_Y HEclObsy_Z
50100.3667202778 141.7345395252 23.7888668056 0.0931686085 -0.5226827384 0.9352821948 0.0134626490 -0.0099268047 -0.0159214543 -0.0008574426 -0.4557464972 0.8718924324 -0.0000157501

**Comment by stevechesley** [comment]
So that difference is an along track error. The 5500 km error becomes <20 km if we move 169 sec along the velocity. I could figure out which way, but I doubt it's important.

So it does not look like a time scale issue, and probably not reference frame again. This looks like dynamical model discrepancy. Or perhaps numerical error. Maybe we should check to make sure that oorb has tight enough error tolerances set?

**Comment by mgranvik** [comment]
The oorb dynamical model accounts for perturbations by the 8 planets and the 
Moon. Both ephemerides and GMs for the 9 perturbers come from de405.

OpenOrb also accounts for relativistic correction but it does not explain the 
discrepancy.

**Comment by mgranvik** [comment]
I've dusted off my Gauss-Radau integrator to make some comparisons. Below you 
can see that the Bulirsch-Stoer and the Gauss-Radau integrators produce 
essentially identical results. The caveat is that they both use the same 
subroutine to calculate the force function. Will dig into that next.


Bulirsch-Stoer

MJD_UTC/UT1       RA              Dec            Delta         HEclObj_X 
HEclObj_Y     HEclObj_Z     HEclObj_dX/dt  HEclObj_dY/dt  HEclObj_dZ/dt 
HEclObsy_X     HEclObsy_Y    HEclObsy_Z
50100.3667202778  141.7351361713  23.7886163166  0.0931690460  -0.5226837315 
0.9352817981  0.0134626072  -0.0099267871  -0.0159214630  -0.0008574428 
-0.4557464972  0.8718924324  -0.0000157501


Gauss-Radau

MJD_UTC/UT1       RA              Dec            Delta         HEclObj_X 
HEclObj_Y     HEclObj_Z     HEclObj_dX/dt  HEclObj_dY/dt  HEclObj_dZ/dt 
HEclObsy_X     HEclObsy_Y    HEclObsy_Z
50100.3667202778  141.7351361711  23.7886163167  0.0931690460  -0.5226837315 
0.9352817981  0.0134626072  -0.0099267871  -0.0159214630  -0.0008574428 
-0.4557464972  0.8718924324  -0.0000157501

**Comment by stevechesley** [comment]
Just running some tests on my end. I find that turning off asteroid perturbations (CPV) leads to a 70 km jump in the state. Not enough to explain the 169 sec problem. 

There is a 0.013 au Earth encounter in the middle of the propagations:

**Comment by stevechesley** [comment]
========= Close Approach Summary =========
    Time (TDB)     Date (TDB)      Body    CA Dist   Vinf
  2450110.43843 1996 Jan 27.93843  Earth  0.018155  16.399
  2452844.90244 2003 Jul 24.40244  Earth  0.052069  17.339
  2452878.82733 2003 Aug 27.32733  Mars   0.258343  19.638
  2453399.51148 2005 Jan 29.01148  Earth  0.011373  15.589
  2453551.47230 2005 Jun 29.97230  Mars   0.171568  12.401
  2454262.00238 2007 Jun 10.50238  Mars   0.499900  10.298

**Comment by mgranvik** [comment]
OpenOrb can reproduce the planetocentric distances at the closest encounters 
with Earth and Mars:

Planetary encounters by object test (orbit #1) between 2008-1-1.00000 and 1996-1-18.36744:
Closest encounter with Earth   at MJD    53399.000000 TT at a distance of  0.01137307 AU given a stepsize of -.500000 days.
Closest encounter with Mars    at MJD    53551.000000 TT at a distance of  0.17156831 AU given a stepsize of -.500000 days.

Since both of these encounters take place in the beginning of the integration I 
also tried looking at the last Earth encounter in Jan 1996:

Planetary encounters by object test (orbit #1) between 1996-2-17.36744 and 1996-1-18.36744:
Closest encounter with Earth   at MJD    50109.950773 TT at a distance of  0.01818929 AU given a stepsize of -.083333 days.

The difference between Horizons and OpenOrb during the last encounter is 
approximately 5100 km.

Can we do a plot showing how the difference between OpenOrb and Horizons grows 
with time? I would like to understand if the divergence starts immediately or 
only after the first Earth encounter.

**Comment by stevechesley** [comment]
I have a file of states. I don't seem to have permission to attach here and so I will send it by email.

It is DE405-based. No asteroid perturbers. 10-day time steps.

**Comment by mgranvik** [comment]
I've found the source for the remaining discrepancy - the mass of the Earth was 
off by a few percent. OpenOrb was computing the mass of the Earth as

M_e = M_e+m * (1 - 1/emrat)

when the correct way is

M_e = M_e+m / (1 + 1/emrat)

With the above change, de430 ephemerides, 8 planets, and relativistic 
corrections, I get these ephemerides:

MJD_UTC/UT1       RA              Dec            Delta         HEclObj_X      HEclObj_Y     HEclObj_Z     HEclObj_dX/dt  HEclObj_dY/dt  HEclObj_dZ/dt  HEclObsy_X     HEclObsy_Y    HEclObsy_Z
50100.3667202778  141.7114441895  23.7962102303  0.0931761502  -0.5226630830  0.9353136881  0.0134642265  -0.0099270651  -0.0159210221  -0.0008574242  -0.4557464944  0.8718924338  -0.0000157449

Now, comparing to JPL results the RA and Dec coordinate differences are just 
milliarcsecs or less:

(141.7114441895-141.711445111090)*3600
-.003317724000
(23.7962102303-23.796210404254)*3600
-.000626234400

Steve and Lynne: thank you very much for your persistence in locating this bug! 
I owe you some drinks.

**Comment by rhiannonlynne** [comment]
This is great Mikael! I'm trying to update my version and check how everything works for me. 
I was wondering if I needed an update to the oorb.conf file?  I'm assuming I could put de430.dat in for the planetary ephemeris file, but do I need to change the list of perturbers?

**Comment by mgranvik** [comment]
I think the results are almost identical even with de405. If you nevertheless 
want to go for de430 you just need to change 'de405.dat' to 'de430.dat' in the 
conf file. (Obviously you need to make sure that you have de430.dat available - 
I have updated the Makefile in data/JPL_ephemeris/ so that you can easily 
build it locally.)

Note that the relative error in the mass for the Earth was not 'a few percent' 
as I wrote in my previous message, but about 0.015%.

**Comment by rhiannonlynne** [comment]
I can repeat your match for this object. Test comparison issue is fine to be closed, from my point of view. 
Thanks very much!
