### ISSUE TITLE
Citation and licensing information

### ISSUE THREAD

**Issue by rhiannonlynne** [oorb/oorb#30]
It would be convenient for users (and advantageous for the authors!) to add citation instructions to the README. 
(Example: "Please cite XX when using this software. " )
Would XX = http://adsabs.harvard.edu/abs/2009M%26PS...44.1853G or should it be http://ascl.net/1502.002 ? 

In order to understand how this software is available for redistribution (if at all), it would also be very helpful to add a license. Some reference material - https://opensource.org/licenses 
BSD-3 seems pretty reasonable and popular, and allows redistribution of the software.

**Comment by mgranvik** [comment]
Thanks for pointing this out, Lynne.

Although the licensing information is found in the header of each OpenOrb file 
(GPLv3) and the PDF documentation contained (outdated!) citation information, I 
have updated the README file as you suggested.

Mikael

**Comment by rhiannonlynne** [comment]
Great! Thanks. I didn't realize there was licensing information in each file (should've noticed), but it does make it super easy if it's on the README :)
