### ISSUE TITLE
Use curl instead of wget

### ISSUE THREAD

**Issue by rhiannonlynne** [oorb/oorb#32]
Hi Mikael, 

wget is used in the makefile to generate the JPL ephemeris files, however curl is more widely available, particularly on macos. One option would be to do something like what we've done here - https://github.com/lsst/oorb/pull/8 - but you may have other solutions you prefer.

**Comment by mgranvik** [comment]
Hi Lynne,

I'm okay with the change from wget to curl. Is there gittish way of doing it through a PR or should I just copy-paste your patch to the Makefile?

Mikael

**Comment by rhiannonlynne** [comment]
I think the thing to do is for me to make a new branch from our master (which tracks your master), then cherry pick that commit into that branch , then request a pr from that new branch. That way the same commit exists everywhere and doesn't get duplicated, is what I understand.

**Comment by rhiannonlynne** [comment]
I'll do that today.

**Comment by rhiannonlynne** [comment]
PR submitted : https://github.com/oorb/oorb/pull/33

**Comment by mgranvik** [comment]
PR accepted
