### ISSUE TITLE
Syntax Error enocuntered with source member oorb.f90

### ISSUE THREAD

**Issue by OrbitalMechanic** [oorb/oorb#44]
Attempted to build oorb on Mac Pro (late 2013) running Mac OS X Sierra (ver. 10.12.6) with the latest release. The problem I'm seeing at present is with source member oorb.f90 on line 5060. For whatever reason gfortran thinks it's a syntax error, but from what I see, the syntax seems to be okay. Am I missing something here?

Please advise,

Sam Dupree.

[problem_source_oorb.f90.txt](https://github.com/oorb/oorb/files/1621213/problem_source_oorb.f90.txt)

**Comment by mgranvik** [comment]
Apologies for that. I accidentally introduced the bug yesterday *after* I had tested that the code compiles correctly. It's fixed now with #45
