### ISSUE TITLE
lsl output completely broken

### ISSUE THREAD

**Issue by Siltala** [oorb/oorb#48]
As of now, at least for me, lsl fails to output any orbits at all (!!!!) which seems like a rather critical bug. I did some debugging, and this appears to be a regression caused by commit 4a3d8780bf041dc4b48100bcc7bad9274af07d5f. Line 5062 seems to add an ELSE-CYCLE block if there isn't a significant amount of outliers. This cycle statement in turn causes the code to completely skip the output routines within lsl.

I got around this by simply commenting out the troublesome ELSE block, and things work fine for me again. I don't know if this is the proper fix, but it doesn't look like there's any reason whatsoever to have the ELSE block there. If you think it's fine, I can submit a PR for this.

**Comment by mgranvik** [comment]
Fixed by #49
