### ISSUE TITLE
lsl never (?) prints out "observation_sets_with_many_outliers" file

### ISSUE THREAD

**Issue by Siltala** [oorb/oorb#53]
It looks like the fix for #48 has led to another bug:

When lsl fails due to too many outliers, it is supposed to print out some information about the data into a "observation_sets_with_many_outliers" file. Currently, this never seems to happen and no file is made.

I debugged this, and believe I know the reason:
The data printing is behind an if clause (oorb.f90 line 5117: IF (j == SIZE(orb_arr,dim=1)) THEN )
where the intent is to only print out the data if this was the final orbit tested for the object.
However, "j" actually does -not- represent what the clause think it does: instead, j should be be the total amount of observations in the observation set due to the DO loop in line 5106 also making use of the j variable.
Thus the code will never actually go to the if clause and print out the data.

**Comment by mgranvik** [comment]
Fixed by #54
