### ISSUE TITLE
Make file for JPL Ephemeris

### ISSUE THREAD

**Issue by mrgeorgeschafer** [oorb/oorb#86]
Hello OpenOrb developers,

I've run into what appears to be an inconsistency in documentation: 

On page 5 of the OpenOrb Tutorial v.0.2 (the pdf download), the instructions say to use the command 'make de405' to create the JPL planetary ephemeris file de405.dat; however, this command did not work for me. I used the command 'make ephem' instead, which proved successful. 

Many thanks,
George

**Comment by oorb** [comment]
Hello George,

thanks for letting us know about the misleading information. The relevant part had been fixed in the LaTeX source code, but the PDF had unfortunately not been updated. To prevent this from happening again I decided to remove the PDF from the repository.

Best regards,
Mikael
