### ISSUE TITLE
Problem with random-walk ranging 

### ISSUE THREAD

**Issue by fedorets** [oorb/oorb#87]
When performing with a deb-inclined configuration of gfortran, the task 

cd test
oorb --conf=oorb.conf --task=ranging  --flavor=random-walk --obs-in=K08K42V_ranging.mpc --orb-out=K.orb
results in the following error

At line 7020 of file ../classes/StochasticOrbit_class.f90
Fortran runtime error: Array bound mismatch for dimension 1 of array 'rms' (3/6)

This is a problem with the newest release, everything seems fine with the ancient (one year old?) version.

**Comment by Siltala** [comment]
Hi Grigori,

I had a look at this one and can't reproduce the bug using the command you gave above (with the default configuration file). Can you check if the issue still persists for you with the latest code?

**Comment by Siltala** [comment]
Sorry, I take that back.
With a debug build (and only a debug build) I can reproduce the problem.
The rms values that are computed in the troublesome line are actually not used anywhere, so what I think is happening is that the compiler sees that result is not actually used anywhere and optimizes it out entirely. I will submit a PR with a proposed fix.
