### ISSUE TITLE
'make depends' fails to run

### ISSUE THREAD

**Issue by Siltala** [oorb/oorb#89]
It looks like `make depends` completely fails to run for me at the moment. This is probably related to the new build system (tagging @mjuric )

The failure will result in a blank make.depends file which completely breaks the build process (but can be fixed by reverting to the make.depends file that is in git)

Terminal output:
```
make depends
make -C build depends
rm -f *.o *.mod *.tmp
rm -f version.h
rm -f ../main/oorb ../main/ephemeris_linking ../main/orbit_linking
rm -f ../lib/liboorb.{dylib,a}
rm -rf *.pyf ../python/pyoorb.{so,dylib} ../python/pyoorb.*.so ../python/pyoorb.{name,sp_dir} _pyoorb_build
rm -rf ../bin ../lib
find .. -name '*.gcno' -o -name '*.gcda' -o -name '*.gcov' -exec rm {} \;
generate-version-h.sh $(cat ../VERSION) > version.h
make-fortran-deps.sh ../modules/parameters.f90 ../modules/utilities.f90 ../modules/random.f90 ../modules/sort.f90 ../modules/statistics.f90 ../modules/functions.f90 ../modules/linal.f90 ../modules/estimators.f90 ../modules/planetary_data.f90 ../modules/cl_options.f90 ../modules/integrators.f90 ../modules/data_structures.f90 ../classes/Base_class.f90 ../classes/Unit_class.f90 ../classes/File_class.f90 ../classes/Time_class.f90 ../classes/Observatory_class.f90 ../classes/SphericalCoordinates_class.f90 ../classes/CartesianCoordinates_class.f90 ../classes/Observation_class.f90 ../classes/Observatories_class.f90 ../classes/Orbit_class.f90 ../classes/Observations_class.f90 ../classes/StochasticOrbit_class.f90 ../classes/PhysicalParameters_class.f90 ../main/io.f90 ../main/oorb.f90 ../main/ephemeris_linking.f90 ../main/orbit_linking.f90 ../python/pyoorb.f90  > make.depends
/Users/lsiltala/yo/oorb/oorb//build-tools/make-fortran-deps.sh: line 9: -cpp: command not found
```

**Comment by mjuric** [comment]
Hi @Siltala , sorry about the problem!

Looks like `make-fortran-deps.sh` doesn't pick up the value of `$FC`. Can you edit `./build/Makefile` and prepend `FC=$(FC)` to the line calling it:
```
depends: clean version.h
        FC=$(FC) make-fortran-deps.sh $(ALLSOURCES) > make.depends
```
and see if this fixes it (if so, I'll send a PR).

PS: this only works with `gfortran` -- `ifort` has bugs with dependency generation :(. I have a comment about that in the Makefile, but I should really explicitly test for it to prevent mistakes...

**Comment by Siltala** [comment]
Hi,
Looks like your suggested change does indeed fix the issue. I wasn't aware about the ifort problem but that is also good to know for the future.

Thanks for the fix!
