### ISSUE TITLE
OORBROOT is not defined.

### ISSUE THREAD

**Issue by Socanal** [oorb/oorb#92]
Since last update, the OORBROOT path is not defined during the build process. Following the exact instructions in the readme file I get this error:

>$ oorb --task=ranging --obs-in=K08K42V_ranging.mpc --orb-out=K08K42V_ranging.orb
>***ERROR***  2 May 2019 12:31:20UTC (File / open) Could not open file (OORBROOT/main/oorb.conf). Error code 2.
>***ERROR***  2 May 2019 12:31:20UTC (oorb) Configuration file missing or error while opening it.

I think is worth fixing it in the build process. Otherwise, a temporaty fix can be just adding a new line in the readme file as follows:

>export OORBROOT=$PWD

specifying that is necessary to be in the root directory.

I also wanted to propose an improvement for the readme file adding the dollar sign to these three commands, as it will save some time for linux beginners:

>export OORB_DATA=$OORBROOT/data
>export OORB_CONF=$OORBROOT/main/oorb.conf
>export OORB_GNUPLOT_SCRIPTS_DIR=$OORBROOT/gnuplot/

**Comment by Siltala** [comment]
The original problem presumably was that OORB_CONF was set as OORBROOT/main/oorb.conf without the dollar sign which would indeed cause that.

I've implemented the suggestions into the installation section of the work-in-progress [oorb wiki](https://github.com/oorb/oorb/wiki) and I think that this bug can finally be closed.
